name: 
  protect-branches
on: 
  create:
    branches:
      - dev
jobs:
  Set-Protection-Main:
    runs-on: ubuntu-latesta
    uses: actions/checkout@v2
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - run: echo "Main branch protection rules triggered by ${{ github.event_name }} event."
      - run: |
              echo '{
                  "required_status_checks": {
                    "strict": true,
                    "contexts": ["contexts"]
                  },
                  "enforce_admins": false,
                  "allow_deletions": false,
                  "required_pull_request_reviews": {
                    "dismissal_restrictions": {
                      "users": ["users"],
                      "teams": ["teams"]
                    },
                    "dismiss_stale_reviews": false,
                    "require_code_owner_reviews": false,
                    "required_approving_review_count": 1
                  },
                  "restrictions": {
                    "users": ["users"],
                    "teams": ["teams"],
                    "apps": ["apps"]
                  }
                }' > /tmp/config-branch-rules
      - run: gh api --method PUT repos/:owner/:repo/branches/main/protection --input /tmp/config-branch-rules >/dev/null
      - run: echo "Main branch protection rules created."
  Set-Protection-Dev:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - run: echo "Setting up protection rules for dev branch."
      - run: |
              echo '{
                  "required_status_checks": {
                    "strict": true,
                    "contexts": ["contexts"]
                  },
                  "enforce_admins": false,
                  "allow_deletions": false,
                  "required_pull_request_reviews": {
                    "dismissal_restrictions": {
                      "users": ["users"],
                      "teams": ["teams"]
                    },
                    "dismiss_stale_reviews": false,
                    "require_code_owner_reviews": false,
                    "required_approving_review_count": 1
                  },
                  "restrictions": {
                    "users": ["users"],
                    "teams": ["teams"],
                    "apps": ["apps"]
                  }
                }' > /tmp/config-branch-rules
      - run: gh api --method PUT repos/:owner/:repo/branches/dev/protection --input /tmp/config-branch-rules >/dev/null
      - run: echo "Dev branch protection rules created."
  Complete-Message: 
    needs: [Set-Protection-Main, Set-Protection-Dev]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository set-up complete. Happy development 🎉!"